@echo off
start CMD /C "load_ab_photoYear.bat"
start CMD /C "load_ab06.bat"
start CMD /C "load_ab16.bat"
start CMD /C "load_bc08.bat"
start CMD /C "load_bc10.bat"
start CMD /C "load_mb05.bat"
start CMD /C "load_mb06.bat"
start CMD /C "load_nb01.bat"
start CMD /C "load_nb02.bat"
start CMD /C "load_nl_photoyear.bat"
start CMD /C "load_nl01.bat"
start CMD /C "load_ns03.bat"
start CMD /C "load_nt01.bat"
start CMD /C "load_nt02.bat"
start /wait CMD /C "load_on02.bat"

start CMD /C "load_pc02.bat"
start CMD /C "load_pe01.bat"
start CMD /C "load_qc01.bat"
start CMD /C "load_qc02.bat"
start CMD /C "load_qc03.bat"
start CMD /C "load_qc04.bat"
start CMD /C "load_qc05.bat"
start CMD /C "load_sk01.bat"
start CMD /C "load_sk02.bat"
start CMD /C "load_sk03.bat"
start CMD /C "load_sk04.bat"
start CMD /C "load_sk05.bat"
start CMD /C "load_sk06.bat"
start CMD /C "load_yt02.bat"
