---  
title: "HDR Attributes"
output:  
  html_document:  
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    css: styles.css
---  

<br>

# What's new

  * Added CAS_04 HDR records since they are different from CASFRI specs (2019-05-21)

<br>

# Overview

  * The CASFRI attribute names for CAS_04 are very different from the specifications.
  * It might be easiest to create this table manually since there is no need to loop over all records

<br>

# CAS_04 Attributes

```{r echo=FALSE, message=FALSE, warning=FALSE}  
z = read_csv("cas04_hdr.csv") %>% filter(header_id=="AB_0016")
dfSummary(z, graph.col=FALSE, valid.col=FALSE)
```

<br>

# CAS_05 Attributes

  * If the decision is to use the CAS_04 attributes rather than the attributes in the CASFRI specifications documents then the following sections can be deleted.

## identification_id {.tabset}

  * nothing()

## jurisdiction {.tabset}

  * copyText('AB')

## coordinate_sys {.tabset}

  * nothing()

## projection {.tabset}

  * nothing()

## datum {.tabset}

  * nothing()

## inventory_owner {.tabset}

  * copyText('CANFOR')

## land_owner {.tabset}

  * copyText('INDUSTRY')

## permission {.tabset}

  * nothing()

## tenure_type {.tabset}

  * nothing()

## inv_type {.tabset}

  * copyText('AVI')

## inv_version {.tabset}

  * copyText('2.1')

## inv_start_yr {.tabset}

  * nothing()

## inv_finish_yr {.tabset}

  * nothing()

## inv_acq_id {.tabset}

  * nothing()

## inv_acq_yr {.tabset}

  * nothing()

## inv_update_yr {.tabset}

  * nothing()
