---  
title: "Inventory Notes"
output:  
  html_document:  
    toc: true
    toc_float:
      collapsed: false
    css: styles.css
---  

<br>

# What's new

Last updated: 2019-05-20

<br>

# Bookmarks

* <a href="https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/data-management-and-access">Data Management and Access</a>
* <a href="https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/data-management-and-access/vri-data-standards">VRI Data Standards</a>
* <a href="https://catalogue.data.gov.bc.ca/dataset/vri-forest-vegetation-composite-polygons-and-rank-1-layer">VRI Polygons and Rank 1 Layer</a>
* <a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/data-management/standards/forest_management_land_base_definition.pdf">Forest management land base definition</a>

<br>

# General

  * The latest BC inventory database includes all inventory standards but not all attributes apply to all standards.
  * This is particularly relevant to NFL and ECO attributes. See those sections for more details.
  * What class is "L" in FOREST_INVENTORY_CD and should we include it or not?
  * TFL 48 is not included in the BC inventory except for a few polygons (recent disturbances?)
  * Spatial overlap among attribute groups (based on BC_082E translated files from CAS_04):
    * There is full overlap between LYR and DST polygons.
    * There is no overlap between LYR and NFL polygons.
    * There is no overlap between NFL and DST polygons.
    * There is partial overlap between LYR and ECO polygons.
    * There is partial overlap between NFL and ECO polygons.
    * There is partial overlap between DST and ECO polygons.

<br>

# NFL attributes

In CAS_04, the NFL and LYR polygons all have a unique CAS_ID implying that a polygon is either forested or non-forested. The VRI inventory, however, allows for sub-polygon components that are forested, non-forested, non-vegetated or anthropogenic. There can be 3 components and they must cover at least 10% of the polygon area each. These components are useful when finer polygons cannot be digitized.

  * Is the intent of CASFRI to keep a separation of forested vs non-forested polygons or is it desirable to maintain information at the sub-polygon level? The latter would imply that there could be NFL polygons or NFL components within LYR polygons.
  * Are NFL attributes meant to be exclusive i.e., the polygon is considered entirely one non-forest type? For example, currently it seems that if there is a species_1 there is no NFL attributes.
  * From Appendix 12: "CAS Translation (Whenever a forest inventory includes crown closure for a non-forested attribute - then migrate into CROWN CLOSURE LYR field)". Does this mean that NFL attributes = "NULL_VALUE" if the crown closure field is not NULL?
  * It might make more sense to use the new FOR_MGMT_LAND_BASE_IND to distinguish NFL from LYR attributes (see section below)
  * Are forested (LYR) and non-forested (NFL) layer translated independently i.e., a polygon can have both types of attributes?
  * CASFRI specifies UNPRODUCTIVE_FOREST with 6 values but the CAS_04 only has PRODUCTIVE_FOR with 2 values ("PF","PP"). Why is that?
  * The Perl code (NFL section) calculates $UnProdFor from NON_FOREST_DESCRIPTOR
  * The Perl code (NFL section) uses is.na(species_cd); however, we changed that to for_mgmt_land_base_ind = N to reflect the BC VRI recommendation.

Notes on BC inventory attributes:

  * there are 3 land cover components (e.g., land_cover_class_cd_1) but no corresponding percent attributes, so we cannot tell how extensive each component is within a polygon. The Photo Interpretation Procedures manual suggests these 6 attributes exist plus an additional one for all other components (pct).
  * there are 3 non vegetation cover types (e.g., non_veg_cover_type_1) along with 3 corresponding percent (e.g., non_veg_cover_pct_1) and pattern (e.g., non_veg_cover_pattern_1) attributes. In contrast to land cover components these only track non-vegetation types.

Definitions from VRI photo interp guide:

  * Non-Treed polygon: a polygon is considered Non-Treed if less than 10% by crown cover of the polygon area consists of tree species of any size.
  * Non-vegetated categories: the fifth level of the B.C. Land Cover Classification Scheme. This classifies the polygon into one of a number of specific categories of Non-Vegetated cover.
  * Non-Vegetated cover types: the fourth level of the B.C. Land Cover Classification Scheme. This classifies the polygon as Snow / Ice, Rock / Rubble or Exposed Land if Non-Vegetated. The Non-Vegetated cover type is left blank for water features.
  * Non-Vegetated polygon: a polygon is considered Non-Vegetated when the total cover of trees, shrubs, herbs, and bryoids (other than crustose lichens) covers less than 5% of the surface area of the polygon. Bodies of water are included in this class.

## FRI attributes

It's not clear that the Perl code and our implementation is correct or what is intended (see previous comments/questions). It might be better to have 2 sets of NFL attributes:

  1. Polygon-level based on BCLCS 1-5
  2. Sub-polygon-level based on the attributes we used here.

**for_mgmt_land_base_ind**

Forest Management Land Base Indicator (FMLB) is an attribute field to indicate whether the polygon is forested or has been forested and is capable of producing a stand of trees [for_mgmt_land_base_ind]. This allows the user to filter out polygons that are traditionally considered non-productive such as lakes, rock and alpine. Polygons that have harvest history are included in the FMLB as well as any polygon with a site index greater than or equal to 5.

The FMLB indicator is defined based on the following criteria:

  - Opening Indicator = Y; polygon is considered forest,
  - Opening Indicator = N, but history data indicates logging; polygon is considered forest,
  - BCLCS level 1 = U (no data); polygon is considered non-forest,
  - BCLCS level 1 = A (alpine); polygon is considered non-forest,
  - Non-productive descriptor is not null; polygon is considered non-forest, and
  - Site Index >= 5; polygon is considered forest. 

This is an attempt to replicate how this attribute was created.

<pre>
library(tidyverse)
# Replicate forest management land base indicator (FMLB; see PDF)
xx = mutate(x, 
    logging=if_else(substr(line_7b_disturbance_history,1,1)=="L",1,0),
    logging=if_else(is.na(logging),0,logging),
    fmlb = if_else(
    (substr(line_7b_disturbance_history,1,1)=="L" & site_index>=5) |
    (inventory_standard_cd %in% c("F") & is.na(non_productive_descriptor_cd) & site_index>=5) |
    (inventory_standard_cd %in% c("V","I","L") & !bclcs_level_1=="U") &
    (!bclcs_level_3=="A" & site_index>=5), 1, 0))
table(x$fmlb, x$logging)
</pre>

**non_veg_cover_type_1**

  * Mostly used with inventory_standard_cd = "V"
  * This set of attributes describes the portion of the polygon that is non-vegetated (vegetation cover is less than 5% of the total surface area of the polygon) and is not obscured by vegetation or shadows.
  * Non-vegetated cover types are the designations (from BCLCS level 5) for all observable non-vegetated land cover within the polygon. Note that the level 4 non-vegetated cover type codes (SI-Snow/Ice, RO-Rock/Rubble and EL-Exposed Land) are no longer acceptable for this attribute.
  * A maximum of five (5) non-vegetated attributes are acceptable per polygon.
  * DW = Down Dead Wood

**land_cover_class_cd_1**

  * Mostly used with inventory_standard_cd = "V"
  * Land Cover Components (LCC's) allow detailed description of cover complexes that occur within polygons. Up to three LCC's can be defined within a polygon, and are ranked based on percent cover (total = 100%). Attributes for each LCC include cover codes from either level 4 or 5 of the BCLCS, plus a reporting of soil moisture regime based on nine classes. If more than three components exist, the remaining percent cover is added to the largest LCC.
  * Includes additional non-vegetated types: SI, RO, EL that are not in non_veg_cover_type_1
  * Where are the LCC% attributes? If not there, then we can only use the first component as an indicator of the presence of that component.

**bclcs_level_4**

  * Use with all inventory_standard_cd (F, V, I, L)
  * Provides a single classification for an entire polygon and is used for broad scale land cover reporting (therefore may not be that useful, esp. if we're using LCCs)
  * Missing a few classes e.g., rivers and lakes; this is fine for V where this is covered in the other 2 attributes but not for F. bclcs_level_5 records these 2 classes as RI and LA.

**non_forest_descriptor**

  * Use with inventory_standard_cd = "F"

**non_productive_descriptor_cd**

  * Use with inventory_standard_cd = "F"
