---  
title: "DST Attributes"
output:  
  html_document:  
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    css: styles.css
---  

<br>

# What's new

<br>

# Overview

<br>

# Attributes

## dist_1 {.tabset}

```{r echo=TRUE, message=FALSE, warning=FALSE}
```

### RAWFRI
```{r echo=FALSE, message=FALSE, warning=FALSE}  
dfSummary(x[""], graph.col=FALSE, max.distinct.values=20)
```

### CASFRI
```{r echo=FALSE, message=FALSE, warning=FALSE}  
#dfSummary(x["dist_1"], graph.col=FALSE, max.distinct.values=20)
```

## dist_yr_1 {.tabset}

```{r echo=TRUE, message=FALSE, warning=FALSE}
```

### RAWFRI
```{r echo=FALSE, message=FALSE, warning=FALSE}  
#dfSummary(x[""], graph.col=FALSE, max.distinct.values=101)
```

### CASFRI
```{r echo=FALSE, message=FALSE, warning=FALSE}  
#dfSummary(x$dist_yr_1, graph.col=FALSE, max.distinct.values=101)
```

## dist_ext_upper_1, dist_ext_lower_1 {.tabset}

  * value = -8888 in cas04

## dist_2 {.tabset}

* value = "-8888" in cas04

## dist_year_2 {.tabset}

* value = -8888 in cas04

## dist_ext_upper_1, dist_ext_lower_1 {.tabset}

* value = -8888 in cas04

## dist_3 {.tabset}

* value = ""-8888" in cas04

## dist_yr_3 {.tabset}

* value = -8888 in cas04

## dist_ext_upper_1, dist_ext_lower_1 {.tabset}

* value = -8888 in cas04

## layer {.tabset}

  * value = 1 in cas04
