---
title: "CASFRI"
output:
  html_document:
    toc: false
    toc_float: false
---

# List of publically available FRI datasets

CASFRI is designed so users can build their own standardized forest inventory using the data they have available. The following is a list of publically available datasets from jurisdications across Canada. Other datasets may be available to users by requesting them from the appropriate data providers.

### British Columbia
Current and historical version of the BC Vegetation Resource Inventory are available from the <a target="_blank" rel="noopener noreferrer" href="https://catalogue.data.gov.bc.ca/group/vegetation-resource-inventory">BC data catalogue</a>.

### Manitoba
Data from the Manitoba Land Initiative is available from their <a target="_blank" rel="noopener noreferrer" href="https://mli2.gov.mb.ca/forestry/index.html">web portal</a>.

### Prince Edwards Island
Some older inventory datasets are available through the PEI <a target="_blank" rel="noopener noreferrer" href="http://www.gov.pe.ca/gis/index.php3?number=77555&lang=E">GIS Data catalogue</a>.

### New Brunswick
The latest inventory data is available through the <a target="_blank" rel="noopener noreferrer" href="http://www.snb.ca/geonb1/e/DC/catalogue-E.asp">GeoNB Data Catalogue</a>.

### Nova Scotia
The current forest inventory is available from <a target="_blank" rel="noopener noreferrer" href="https://novascotia.ca/natr/forestry/gis/forest-inventory.asp">government website</a> along with older versions of the inventory.

### Quebec
The most up-to-date inventory files are available for download from the <a target="_blank" rel="noopener noreferrer" href="https://www.donneesquebec.ca/recherche/dataset/carte-ecoforestiere-avec-perturbations">government website</a>.

### Yukon
Yukon's older 5k data as well as their newer 40k data can be downloaded from the GeoYukon <a target="_blank" rel="noopener noreferrer" href="https://mapservices.gov.yk.ca/geoyukon/?&LayerTheme=Forestry">Data Exporer</a>.